version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: ["*"]
    default-days: 7

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-python:
        patterns: ["*"]
    versioning-strategy: lockfile-only
    default-days: 7